name: CB-Heads
version: "4.4.2"
main: Wertzui123\CBHeads\Main
api: 5.0.0
author: Wertzui123
authors: [Wertzui123, Enes5519]
load: STARTUP
permissions:
  cb-heads.command.head:
    description: Permission for the /head command
    default: op
  cb-heads.bypass.waiting:
    description: Permission to bypass the head claim cooldown
    default: op
  cb-heads.bypass.blacklist:
    description: Permission to get heads from players on the blacklist
    default: false