---
# Only change this if you know what you're doing!
config-version: 3.1

# Command
command:
 command: "head"
 description: "Gives you the head of a player"
 usage: "/head <player: target>"
 aliases: ["playerhead"]

# Other data
head_format: "ยงrยง6{name}'s Head"
drop_on_killed: false # when enabled, players will drop their heads when killed by another player
drop_on_suicide: false # when enabled, players will drop their heads when killed by themselves
blacklist: []

# The time how long the players have to wait before claiming a head again, in seconds
# 86400 seconds is one day
wait_time:
 default: 86400 # this is the default
 vip: 43200 # players need the permission cb-heads.waiting.vip to wait this long
...